import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import NavBar from "../components/Navbar";
import { CryptoProvider } from "../context/CryptoContext";
import { PortfolioProvider } from "../context/PortfolioContext";
import Footer from "../components/Footer";
import { ThemeProvider } from "next-themes";
import { CurrencyProvider } from "@/context/CurrencyContext";

export const metadata: Metadata = {
  title: "Crypto-Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="images/crypto_tracker_logo.ico" />
      </head>
      <body className={`bg-cover bg-center`}>
        <CurrencyProvider>
          <CryptoProvider>
            <PortfolioProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem={true}
                disableTransitionOnChange={true}
              >
                <NavBar />
                {children}
                <Footer />
              </ThemeProvider>
            </PortfolioProvider>
          </CryptoProvider>
        </CurrencyProvider>
      </body>
    </html>
  );
}
