import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/Navbar/NavBar";
import { CryptoProvider } from "./context/CryptoContext";
import { PortfolioProvider } from "./context/PortfolioContext";
import Footer from "./components/Footer/Footer";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Crypto-Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/crypto_tracker_logo.ico" />
      </head>
      <body className={`bg-cover bg-center`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light" // Thème forcé pour éviter les conflits hydratation
          enableSystem={true} // active la détection automatique du système
          disableTransitionOnChange={true}
        >
          <NavBar />
          <CryptoProvider>
            <PortfolioProvider>{children}</PortfolioProvider>
          </CryptoProvider>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
